name: OnlyMyWay
main: OnlyMyWay\OnlyMyWay
author: ZINGDING
version: "1.0-release"
api:
- 1.12.0
- 1.13.1
- 1.14.0
- 1.8.0
- 1.6.0
- 1.4.0
- 2.8.0
- 2.0.0

permissions:
  onlymyway.join:
    default: op
